name: CI

on:
  push:
    branches:
      - master

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, build
        run: |
          npm install
      - name: run Lighthouse CI
        env:
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
          LHCI_NAME: ${{ secrets.LHCI_NAME }}
          LHCI_PASS: ${{ secrets.LHCI_PASS }}
        run: |
          npm install -g @lhci/cli@0.4.x
          lhci autorun
